---
title: "Parse cogaps out"
author: "Kyla Woyshner"
date: "2/26/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fgsea)
library(dplyr)
library(ggplot2)
```

####### LOAD AND PARSE DATA ########
```{r}
NMF <- readRDS('/mnt/morbo/Data/Users/kwoyshner/cerebellum/results/mouse_allGenes_n15/mouse_CB_cogaps_n15_nIterations20k.RDS')
savename <- 'mouse_CB_cogaps_n15_nIterations20k'
```


```{r}
# P matrix = samples x Patterns
sampleWeights<-t(NMF@sampleFactors) # patterns x samples
# A matrix = genes x Patterns
geneWeights<-NMF@featureLoadings
```


############## FGSEA HELPER FUNCTIONS ####################
```{r}
run_fgsea_on_matrix_geneWeights <- function(gene_sets, expression_matrix, scoreType) {
  col_names <- colnames(expression_matrix)
  cat("Processing expression matrix with", ncol(expression_matrix), "columns.\n")
  # Use sapply to iterate over each column of the matrix
  results <- sapply(seq(ncol(expression_matrix)), function(col_index) {
    cat("Running fgsea for", col_names[col_index], "\n")

    # Use tryCatch to handle errors during fgsea
    tryCatch({
      fgsea_results <- fgsea(gene_sets, expression_matrix[, col_index], scoreType = scoreType)
      return(fgsea_results)
    }, error = function(err) {
      # Handle the error as needed
      warning(paste("Error in column", colnames(expression_matrix)[col_index], ":", conditionMessage(err)))
      return(NULL)
    })
  }, simplify = FALSE)

  names(results) <- colnames(expression_matrix)
  return(results)
}

```

```{r}
plotFGSEA <- function(fgsearesult, pvalue.cut = NULL, size.cut = NULL, max.size.cut = NULL, n_pathway = NULL){
  #set default pvalue if not provided
  if(is.null(pvalue.cut)){
    pvalue.cut <- 0.05
  }

  #set default size if not provided
  if(is.null(size.cut)){
    size.cut <- 1
  }

  #set default size if not provided
  if(is.null(max.size.cut)){
    max.size.cut <- 500
  }

  #stop plotting if no pathways are significant
  if(min(fgsearesult$padj > pvalue.cut, na.rm = TRUE)){
    warning("No pathways reach significance")
  }

  #warn if there are no pathways above designated size cutoff and revert to a size of 1
  if(size.cut > max(fgsearesult$size, na.rm = TRUE)){
    warning("No pathways above designated size cutoff, reverting to default size of 1...")
    size.cut <- 1
  }

  #tidy results
  if(!is.null(fgsearesult)){
    fgseaResTidy <- fgsearesult %>% subset(padj <= pvalue.cut & size >= size.cut & size <= max.size.cut) %>%
      as_tibble() %>%
      dplyr::arrange(desc(size))
    #take top n_pathways by size
    if(!is.null(n_pathway)){
      fgseaResTidy <- head(fgseaResTidy, n = n_pathway)
  }}

  #stop if there are no pathways given the supplied p value and size cutoff
  if(dim(fgseaResTidy)[1] == 0){
    warning("No pathways given pvalue and size cutoff")
  }

  EnrichmentPlot <- ggplot2::ggplot(fgseaResTidy, ggplot2::aes(reorder(pathway, NES), NES)) +
    ggplot2::geom_point(aes(size=size, color = padj)) +
    coord_flip() +
    labs(x="Pathway", y="Normalized Enrichment Score",
         title="Pathway NES from GSEA") +
    theme_minimal()
  print(EnrichmentPlot)
  #return(list(fgseaResTidy = fgseaResTidy,
  #            EnrichmentPlot = EnrichmentPlot))
  return(fgseaResTidy = fgseaResTidy)
}
```



############ FGSEA ON GO TERMS ###################
########## USE COGAPS GENE WEIGHTS ###############
```{r}
msigdbr_list =  msigdbr::msigdbr(species = "Mus musculus", category = "C5") # C5 is go terms
msigdbr_list_GO = msigdbr_list %>%
  dplyr::filter(gs_subcat != "HPO")
pathways = split(x = msigdbr_list_GO$gene_symbol, f = msigdbr_list_GO$gs_name)

fgsea_human_CB_GO <- run_fgsea_on_matrix_geneWeights(pathways, geneWeights, scoreType = "pos")
saveRDS(fgsea_human_CB_GO, paste0(savename, "_fgseaGO_geneWeights.RDS")) # SAVE RDS OF THIS

require(openxlsx)
write.xlsx(fgsea_human_CB_GO, file = paste0(savename, "_fgseaGO_geneWeights.xlsx")) # SAVE DF OF THIS

```


```{r}
pdf(paste0(savename, "_fgseaplots_GO_geneWeights.pdf"),width=8)
tidy <- lapply(fgsea_human_CB_GO, plotFGSEA)
dev.off()

write.csv(tidy, paste0(savename, "_fgseaGO_geneWeights_thresh.csv"))
```
